### ISSUE TITLE
刮削器把是中文的资源和不是中文的全部重命名为中文的

### ISSUE THREAD

**Issue by Leonyan938** [junerain123/javsdt#10]
大大，反应一个问题   请看下图   我有三个测试的资源，然后其中两个是中文字幕资源，一个是普通无字幕资源，番号命名如下
<img width="456" alt="image" src="https://user-images.githubusercontent.com/3710665/70953702-bbc87c00-20b1-11ea-81fb-e79aa3fe0ce9.png">
然后在用软件整理完后，那个不是中文字幕的资源ABP-118也会被重命名为ABP-118-C，且nfo里的title也是被命名为ABP-118-C   只不过没有中文字幕的标签
<img width="608" alt="image" src="https://user-images.githubusercontent.com/3710665/70953603-65f3d400-20b1-11ea-86eb-198a1e6fe165.png">
<img width="1150" alt="image" src="https://user-images.githubusercontent.com/3710665/70953635-7dcb5800-20b1-11ea-9c22-b9c9c306bfdc.png">
以下是我的ini配置信息
<img width="600" alt="image" src="https://user-images.githubusercontent.com/3710665/70953886-8c663f00-20b2-11ea-85c4-0a61be35df92.png">

请问这是bug吗？还是我的设置有问题？

谢谢啦

**Comment by Leonyan938** [comment]
找到原因了   有-c的文件不能和没-c的文件放一个文件夹下，没-c的会被自动加上-c  但是不会有中文字幕的标签

**Comment by junerain123** [comment]
我看了下代码，的确有你所说的问题，有“-C”的文件导致它身边的文件也加上“-C”’，现在我修改代码，修复了这个问题。
  目前判断“中文字幕”还很粗糙。一是视频周围有字幕文件，不管这个字幕是哪一部影片的，二是视频文件名有-c。  下个版本会更好地判定“中文字幕”的条件。
  非常感谢，你提问有截图，很详细，还帮我找到了问题所在。

**Comment by Leonyan938** [comment]
哇 效率好高啊  这么快就解决了！   恩恩  期待下一个版本 :)
