### ISSUE TITLE
两个建议和一个bug反馈

### ISSUE THREAD

**Issue by 2173432565** [junerain123/javsdt#19]
建议：
1、javbus有码无码不要分开两个成两个程序，既然能识别是有码无码了，为什么要分开处理呢？
2、如果使用翻译的话，女优名字建议可同时保留中日两种名字
bug:
比如RED105再javbus上面有对应的，最终却选择了RED-105，这两个是不一样的，还有比如TMC-025在javbus上面也有，但是最终会选择TMCY-025，所以建议如果搜索结果有多个的话，尽量优先匹配名字完全一样的

**Comment by junerain123** [comment]
1、有一些用户在使用library整理有码，bus整理无码，不希望整理无码的时候又把有码给整理了，比如我，更喜欢library的有码信息。合并没有问题，只是为了照顾我这样的人。
2、你的第二个问题，我看不懂。是保留成这样吗？古川伊织（古川いおり）。不论是library还是bus整理的，把她们的名字统一起来？我可以未来考虑，抓取信息时，同时去两家网站，把信息尽可能综合起来。
3、加不加“-”，导致结果不一样，这个问题应该是javbus该解决的问题。程序只能从javbus返回给它的数据中找。在javbus搜索“TMC-025”，只能找到“TMCY-025”。但“TMC025”就能找到真正的“TMC-025”，应该让javbus解决这个问题。大多数情况下，javbus返回一个结果（就是想要的结果），还要确定它是不是真正的那个结果，太浪费时间了。但返回多个结果，现在程序的确是找“优先匹配名字完全一样的”。

**Comment by 2173432565** [comment]
@junerain123 1、关于第一点，还有另外一个方案，可以把javbus有码无码和javlibrary三个程序合并成一个程序，然后在配置文件里面增加一个配置项或者多个，比如：是否javlibrary优先：是（默认值），这样有两种执行顺序可选择：
        1.先去javbus查询是有码还是无码，如果是有码根据刚才的配置项来决定去哪个网站获取，如果是无码，用javbus获取；
        2.直接先去javlibrary获取，如果获取不到，再去javbus获取
2、第二点你理解的意思是对的，就是 古川伊织（古川いおり）这样的效果
3、第三点也许网页搜索和接口搜索结果不一样吧，你可以试下在javbus搜索一下TMC-025有三个结果，其中有一个是对的，如果接口查询也是这样的话，那应该按“优先匹配名字完全一样的”逻辑就不会有问题
