### ISSUE TITLE
路径分隔符的一点小建议

### ISSUE THREAD

**Issue by SA-Framework** [junerain123/javsdt#30]
纯属一点小建议😛 看到 readme 里提到了不同系统需要改路径分隔符，其实完全没有必要，改善编码风格就能减少不必要的麻烦。

Linux 下是正斜杠 "/"，Windows 下默认是反斜杠"\\"，为了转义，还会出现双反斜杠"\\\\"。然而，Windows 其实也是是支持正斜杠"/" 的。

此外，建议使用系统无关的分隔符，python 里有os.sep ，可以提高跨系统的兼容性。

**Comment by junerain123** [comment]
好的，很久以后的下个版本会尝试使用。
