### ISSUE TITLE
[bug]扩展名大小写识别错误

### ISSUE THREAD

**Issue by AragonSnow** [junerain123/javsdt#33]
windows下，扩展名大小写不同不会影响使用什么扩展格式，比如.avi和.AVI是同一个东西。配置文件却是区分大小写的，导致部分文件没有被识别出来。望修改

**Comment by junerain123** [comment]
![image](https://user-images.githubusercontent.com/44168897/72099237-2c825180-335b-11ea-8c21-2983d51ce78b.png)

**Comment by junerain123** [comment]
你自己加上。

**Comment by AragonSnow** [comment]
> 你自己加上。

已经加上了，感谢。还是希望在判断格式的时候不区分大小写处理好一点
