### ISSUE TITLE
外挂字幕归档

### ISSUE THREAD

**Issue by fzfile** [junerain123/javsdt#38]
如题，可否增加外挂字幕的补充归档功能，现在貌似只有存在影片的时候才会操作字幕。如果是之后才找到字幕的话只能手动改，或者把影片剪出来重新归档。

**Comment by junerain123** [comment]
现在1.0.4已经加个一个独立的功能“为整理后的影片收集外挂字幕”，你需要下载releases里面的外挂字幕包。如果你有另外的字幕。可以再放进“外挂字幕”包里。

**Comment by horryruo** [comment]
可以增加一个重新编辑信息的exe吗，比如说我想更改了ini，改变了文件名的编排，或者早就加了字幕但是忘记给名字添加中字标记，希望有个exe可以重新根据我更改的ini更新文件的ini和文件名而不用重新获取一遍

**Comment by acios** [comment]
说明里有个“【字幕】为整理过的文件夹收集外挂字幕.exe”，但是新版本1.1.3里面已经没有这个exe文件了，用其它几个整理的过程中也没发现会去读取字幕文件夹并添加，这是咋回事？
