### ISSUE TITLE
希望能够添加对fc2的支持

### ISSUE THREAD

**Issue by interjz4** [junerain123/javsdt#42]
无码界势弱，目前无码反而fc2产出还可以
特别是前段时间的流出也是fc2
希望能够添加对fc2的支持

**Comment by junerain123** [comment]
新版本1.0.4已经增加对fc2的支持，基于javdb。但javdb限制同一IP搜索次数，大概5分钟12次，无论是爬虫还是浏览器。目前效率较低。
