### ISSUE TITLE
nfo的格式的标准是怎么了解的。

### ISSUE THREAD

**Issue by PhilLinGX** [junerain123/javsdt#43]
参考了下代码，表示感谢~
不知道nfo文件里面的数据具体标准是怎么样的。网上描述也不多。用kodi管理的

小建议：我自己写了个scrapy的爬虫把bus上面的所有信息都爬到了本地（4.5小时吧），也就7.8G大小，觉得这么做可以更方便直接本地处理整理的内容。

**Comment by junerain123** [comment]
[The Amazing Spider-Man 2 (2014).zip](https://github.com/junerain123/javsdt/files/4209553/The.Amazing.Spider-Man.2.2014.zip)
我传给你一个kodi下的“超凡蜘蛛侠”的nfo，你看看里面的内容，很全。
你自己建一个“The Amazing Spider-Man 2 (2014).mp4”，再用emby扫描这个电影，看看这个nfo发生了什么变化。
我代码里写nfo，应该把emby能读取的内容都写上去了。emby读不了系列，系列在kodi是“<set>”，比如“超凡蜘蛛侠”这个系列，“一日十射j”这个系列。

**Comment by junerain123** [comment]
还想请教你，怎么爬全站啊？30万部影片，怎么知道它们所有的链接？

**Comment by junerain123** [comment]
系列在kodi是“《set》超凡蜘蛛侠《/set》”

**Comment by leopku** [comment]
@PhilLinGX 能否网盘分享一下？谢谢了先

**Comment by PhilLinGX** [comment]
我是用scrapy写的工程。不敢外传，怕被查水表。2.29一夜之间




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"junerain123"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月16日(星期天) 下午5:06
收件人:&nbsp;"junerain123/javsdt"<javsdt@noreply.github.com&gt;;
抄送:&nbsp;"正元智慧硬件-lgx"<624467649@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [junerain123/javsdt] nfo的格式的标准是怎么了解的。 (#43)




还想请教你，怎么爬全站啊？30万部影片，怎么知道它们所有的链接？
