### ISSUE TITLE
用jav321整理素人时报错

### ISSUE THREAD

**Issue by happywilly** [junerain123/javsdt#45]
>第67个失败！发生错误，如一直在该影片报错请截图并联系作者：\\300ntk-283-C.mp4
Traceback (most recent call last):
  File "suren_jav321.py", line 483, in <module>
KeyError: 'R'

所有的影片都是这个报错

版本  v1.0.1

**Comment by happywilly** [comment]
发现是ini里影片重命名的问题  但是其他几个用这个命名方式都可以，就是jav321不行~

**Comment by junerain123** [comment]
你的命名方式截个图给我看看？

**Comment by happywilly** [comment]
[重命名影片]
是否重命名影片？ = 是
重命名影片的格式 = [+FHD+]+车牌+R

其他的都可以用

但是jav321的就会报错  得把+R去掉

**Comment by junerain123** [comment]
没去细究以前的版本为什么处理不了“R”，现在发布的新版本1.0.4已经解决了这个问题，感谢你的反馈。
