### ISSUE TITLE
如果导入plex使用，多CD时希望能额外生成一组不带-cd2后缀的jpg。

### ISSUE THREAD

**Issue by deadlyedge** [junerain123/javsdt#46]
比如XXXX-cd2-fanart.jpg  --> XXXX-fanart.jpg

这样plex就可以识别图片了。

**Comment by junerain123** [comment]
@deadlyedge 我不太理解，截张图，让我看看文件怎么命名。

**Comment by deadlyedge** [comment]
![Annotation 2020-02-26 000834](https://user-images.githubusercontent.com/35342284/75265693-3c32f800-582c-11ea-99fb-3df145e24aec.png)
红圈内文件名可以被plex识别，只有篮圈文件的话不行。

**Comment by ddd354** [comment]
![best_jav_path](https://user-images.githubusercontent.com/59108201/75266340-33a4d800-57c0-11ea-9796-dfa1f39b62b3.PNG)
其实最佳的方式是直接用 fanart 和 poster, plex/emby都支持同时少了很多要写的code

**Comment by junerain123** [comment]
我在处理图片时，图片是跟随视频命名的，cd2的视频，图片自然也有cd2。这段时间在写1.0.4，尝试解决你说的这个问题，但一时没找到好的办法，这个问题先搁置一下，以后的版本再解决。

**Comment by junerain123** [comment]
1.0.6开始解决了这个问题，现在close。
