### ISSUE TITLE
一部分文件名处理完成后会遗留原文件

### ISSUE THREAD

**Issue by PTAbabybearR** [junerain123/javsdt#48]
类似【hjd2048.com-0428miae228-h264.mp4】的文件
在处理完成后，原文件还会遗留下来不会被删除

**Comment by junerain123** [comment]
这不是遗留，肯定是报错搜索不到这个视频。
因为会先匹配到“hjd2048”，而不是“miae228”，你得事先修改它的文件名。

**Comment by junerain123** [comment]
最近的版本已经可以添加无视这些干扰车牌的文字。
