### ISSUE TITLE
能否在ini设置里加上从哪个网站下载封面

### ISSUE THREAD

**Issue by PTAbabybearR** [junerain123/javsdt#49]
现在DMM访问不了，要失败5次以后才切换到javbus，比较浪费时间。
能否在ini设置里加个下载封面网站的默认项。

    >正在查找简介： https://www.arzon.jp/itemlist.html?t=&m=all&s=&q=DVDMS-166
    >修改文件名完成
    >重命名文件夹完成
    >nfo收集完成
    >正在下载封面： http://pics.dmm.co.jp/mono/movie/adult/dvdms166so/dvdms166sopl.jpg
    >下载失败，重新下载...
    >下载失败，重新下载...
    >下载失败，重新下载...
    >下载失败，重新下载...
    >下载失败，重新下载...
    >从javlibrary下载fanart.jpg失败，正在前往javbus...
    >正在从javbus下载封面： https://pics.javcdn.pw/cover/66s2_b.jpg
    >fanart.jpg下载成功
    >poster.jpg裁剪成功
    >归类文件夹完成

**Comment by junerain123** [comment]
新版本已上线，javlibrary整理 时也会去javbus获取“系列”，顺便用javbus上的 图片下载。
