### ISSUE TITLE
今天下午javlibrary不能使用了

### ISSUE THREAD

**Issue by ppscloud** [junerain123/javsdt#54]
早晨用时还正常，下午不能用了，更新1.04后也是失败，显示打开javlibrary搜索页面失败，正在重新尝试... 空返回... http://www.p42u.com/cn/vl_searchbyid.php，网页是可以正常访问的

**Comment by junerain123** [comment]
![image](https://user-images.githubusercontent.com/44168897/76069505-e8fc3a80-5fcd-11ea-9c1d-77d5f3a2f2b7.png)


的确用不了了，因为这个东西，爬虫暂时过不去了。可能需要想办法通过这个“5秒防刷”。

**Comment by ppscloud** [comment]
javlibrary可以识别mide00001这种番号，javbus不行，这下有点麻烦了
