### ISSUE TITLE
KODI stacked 的电影封面的格式问题

### ISSUE THREAD

**Issue by rrkyd** [junerain123/javsdt#55]
对于Kodi 来说，如果一部电影分为几个部分，那这个电影的fanart的名字里边是不能有“cd1”的，目前程序默认图片和文件的名字一致，所以Kodi无法识别多部份电影的封面。

非常希望能够在下次更新中解决这个问题。多谢！

**Comment by junerain123** [comment]
马上1.0.6解决了这个问题，感谢反馈。
