### ISSUE TITLE
关于重命名的一点小建议

### ISSUE THREAD

**Issue by ClwonLoon** [junerain123/javsdt#56]
功能十分强大，十分好用，感谢作者。不过我遇到一个小问题，有一部本来在javbus上是有车牌的，可能那会网络有问题没有搜到，然后跳到了另一个网站搜索，当时是哪个网站我忘了，但是这个网站是没有这个车牌，软件就自动给我匹配到了另一个完全不同的车牌，(例如我的是xxx-123,结果匹配到了123-xxx,两个是完全不同的影片)，并且我开了文件夹重命名，因为我文件夹里只有个视频文件，导致之后不知道原车牌号是多少了。我建议能否在打开重命名文件夹的情况下，如果匹配到的车牌与原车牌号不同或差距很大（即使已经匹配到车牌并修改成功）也在失败记录里添加一条提示例如：123-xxx匹配到的车牌于原车牌xxx-123不同或差距较大，请注意查看。之类的提示。再次感谢作者

**Comment by junerain123** [comment]
马上新版本1.0.6加上一个功能，所有重命名的jav，用一个txt记录“新文件名 原文件名”。
还有 即使搜索结果只有一个，也会去核对 这个唯一的结果的车牌是不是符合要求。
你说比较它们的差距，分辨123-xxx和xxx-123，做不到。现在判断的依据是，本地车牌和网页上的车牌数字相同、字母也相同，就用这个结果，如果有多个符合结果，再警告用户。
感谢反馈。
