### ISSUE TITLE
建议增加功能：记录本地文件整理信息，刮削信息存档本地，离线整理

### ISSUE THREAD

**Issue by l23cy2020** [junerain123/javsdt#62]
建议新增：
    文件数据库，用于保持本地文件信息，方便检索并批量整理、排序、筛选本地文件，后续可拓展：如：刮削匹配错误信息，可还原原文件名；/同一车牌文件夹，可兼容不同大小的视频文件，低分辨率支持远程、高分辨率支持本地；/等等
    车牌数据库，用于保持刮削车牌信息，方便检索并批量重建刮削的nfo文件，后续可拓展：如：合并不同用户的车牌数据库，根据”云“合并的爬虫信息，建立图书馆，可以本地查询；等等

流程如下，实现三个功能，三个功能相互独立运行：
    1.遍历本地文件夹：
    --根据视频文件逐一生成信息：如原文件名（并制作车牌）、大小、类型、文件创建时间等信息；
    --生成的视频信息，写入文件数据库（如属于新入库，标记为待刮削）；
    2.刮削网络信息：
    --以“待刮削”，检索文件数据库，逐一匹配本地的车牌数据库，如匹配成功，标记已刮削；
    --以“待刮削”，重新检索文件数据库，逐一刮削并车牌信息，如匹配成功，逐一写入车牌数据库；如刮削失败，标记“刮削失败”。
    3.批量整理本地文件：
     以“已刮削”，检索文件数据库，逐一匹配本地的车牌数据库，如匹配成功：制作文件夹、移动视频文件、从头像文件夹按车牌信息复制头像，从字幕文件夹按车牌信息复制字幕等。

**Comment by ddd354** [comment]
其实这个工具感觉更偏向简单易用，功能单一是好事，单纯刮削没有太大必要添加太多功能
如果你真的需要这些功能可以尝试研究一下https://github.com/ddd354/JAVOneStop 你提的功能70%都有 不过这个更偏向管理 而不是刮削工具

**Comment by l23cy2020** [comment]
@ddd354 
对于我这初学者来说，JAVOneStop 用了好多插件，只能mark，慢慢学习了。

**Comment by junerain123** [comment]
你说的很对，我也有这样的愿景，现在的javsdt归根到底就是刮削和os.rename，还有很长的路要走。
我现在为学业、工作、生活所迫，只想赶紧把现在的功能做到稳定版，先放下这个坑。
如果明年，不需要996，javsdt还会一直更新下去，发展成 图书馆+刮削+管理+类emby的多重模式，
希望大家等等我。
