### ISSUE TITLE
Mac下使用python文件无法进行整理，选好文件夹后直接显示完成

### ISSUE THREAD

**Issue by Hessel2333** [junerain123/javsdt#64]
如下图，选择文件夹后，没有进行整理，直接显示完成
![image](https://user-images.githubusercontent.com/31088294/76991235-31c7d200-6984-11ea-8b71-4896c34323dc.png)

**Comment by junerain123** [comment]
![1](https://user-images.githubusercontent.com/44168897/77022527-d10cb980-69c4-11ea-8efe-fdb98fb17a3d.PNG)
![2](https://user-images.githubusercontent.com/44168897/77022531-d23de680-69c4-11ea-8c86-e5898c06c1e1.PNG)
快用新版本1.0.6

**Comment by Hessel2333** [comment]
新版好像没有创建ini文件的py，我用之前的ini运行了，显示未找到cfscrape
![image](https://user-images.githubusercontent.com/31088294/77088921-191cf200-6a40-11ea-8b52-1e0b3105db22.png)

**Comment by Hessel2333** [comment]
> ![1](https://user-images.githubusercontent.com/44168897/77022527-d10cb980-69c4-11ea-8efe-fdb98fb17a3d.PNG)
> ![2](https://user-images.githubusercontent.com/44168897/77022531-d23de680-69c4-11ea-8c86-e5898c06c1e1.PNG)
> 快用新版本1.0.6
新版好像没有创建ini文件的py，我用之前的ini运行了，显示未找到cfscrape
![image](https://user-images.githubusercontent.com/31088294/77088921-191cf200-6a40-11ea-8b52-1e0b3105db22.png)

**Comment by Hessel2333** [comment]
> ![1](https://user-images.githubusercontent.com/44168897/77022527-d10cb980-69c4-11ea-8efe-fdb98fb17a3d.PNG)
> ![2](https://user-images.githubusercontent.com/44168897/77022531-d23de680-69c4-11ea-8c86-e5898c06c1e1.PNG)
> 快用新版本1.0.6

新版好像没有创建ini文件的py，我用之前的ini运行了，显示未找到cfscrape
![image](https://user-images.githubusercontent.com/31088294/77088921-191cf200-6a40-11ea-8b52-1e0b3105db22.png)

**Comment by junerain123** [comment]
抱歉，忘了上传创建ini的py了。

**Comment by junerain123** [comment]
还有，你需要“pip install cfscrape”。
还有，你需要搜索“node.js”并安装，才能使用javlibrary整理。

**Comment by Hessel2333** [comment]
> 还有，你需要“pip install cfscrape”。
> 还有，你需要搜索“node.js”并安装，才能使用javlibrary整理。

已按你所说的全部安装，但是还是不行，尝试了一下emby头像导入，也不行，值得一提的是，py文件中好像还是“女优”而不是“演员”，ini的一些设置也有些差异
![image](https://user-images.githubusercontent.com/31088294/77141135-d4806d80-6ab6-11ea-872a-323f8859d823.png)

**Comment by junerain123** [comment]
我把新的emby_actors.py上传了，你用新的。
需要安装哪些第三方库也写在readme了。
