### ISSUE TITLE
1.0.6封面截取右半边不正确

### ISSUE THREAD

**Issue by ClwonLoon** [junerain123/javsdt#65]
1.0.6截取右半边的尺寸不对，会造成封面不完整

**Comment by junerain123** [comment]
再讲得详细点，我身在庐山，一下子没理解。

**Comment by ClwonLoon** [comment]
就是软件自动下载封面（背景图）后会截取右半边作为封面，截取的尺寸不对，会造成封面不完整

> 再讲得详细点，我身在庐山，一下子没理解。

![WX20200325-024600](https://user-images.githubusercontent.com/51455735/77464981-f2e1c280-6e42-11ea-8bde-eb821dfc9979.png)

**Comment by junerain123** [comment]
1.0.6重写一些代码时，我忘了有码和其他类型的jav裁剪的尺寸不一样，现在1.0.7修复了这个问题。感谢反馈。
