### ISSUE TITLE
請問是否可以增加收集originaltitle這個屬性值，整理片時挺實用的，謝謝

### ISSUE THREAD

**Issue by cougarzee** [junerain123/javsdt#68]
非常喜歡這個程式，幫了大忙
我在整理片時，在title上常會加註一些有的沒的，也會直接寫中文標題，
這時originaltitle這個屬性就很重要了，可以幫我記錄原始的片名。
希望作者可以考慮新增收集originaltitle，
謝謝

ps.我使用plex+xbmcnfomovieimporter整理影片。

**Comment by junerain123** [comment]
好的，记下了，以后加上。

**Comment by cougarzee** [comment]
> 好的，记下了，以后加上。

非常感謝

**Comment by junerain123** [comment]
1.0.8依据加上了originaltitle！

**Comment by junerain123** [comment]
1.0.8已经加上了originaltitle！
