### ISSUE TITLE
【有码】javlibrary.exe 无法通过五秒认证

### ISSUE THREAD

**Issue by gudejbvsoyczqu** [junerain123/javsdt#71]
【有码】javlibrary.exe文件无法通过五秒认证

**Comment by junerain123** [comment]
重新安装[node.js](https://nodejs.org/en/)，重启电脑。
![image](https://user-images.githubusercontent.com/44168897/78260402-8183cd00-7530-11ea-97cb-8d4cddd9f80b.png)

**Comment by gudejbvsoyczqu** [comment]
更新了最新版node.js后可以了，谢谢！

**Comment by Favorskii404** [comment]
重装node.js至最新版本，使用javlibrary.exe后返回
ERROR:root:'http://www.p42u.com/' returned an error. Could not collect tokens.
可能是什么地方有错呢

**Comment by junerain123** [comment]
我是真的没辙了！
局部代理目前是不能通过javlibrary的cf检测的，全局可以。

**Comment by gudejbvsoyczqu** [comment]
现在更新了node.js也不行了。有没有办法用输入token的方式？

**Comment by fz19870823** [comment]
貌似cfscrape挂了，是不是要等那边更新才行了？

**Comment by zs1135** [comment]
https://github.com/Anorov/cloudflare-scrape/issues/347#issuecomment-613920366

cfscrape换成cloadscraper之后能通过验证

**Comment by zheken1978** [comment]
> [Anorov/cloudflare-scrape#347 (comment)](https://github.com/Anorov/cloudflare-scrape/issues/347#issuecomment-613920366)
> 
> cfscrape换成cloadscraper之后能通过验证

怎么换啊，兄弟？

**Comment by zs1231231** [comment]
> > [Anorov/cloudflare-scrape#347 (comment)](https://github.com/Anorov/cloudflare-scrape/issues/347#issuecomment-613920366)
> > cfscrape换成cloadscraper之后能通过验证
> 
> 怎么换啊，兄弟？

windows下打包好的程序咋换我不知道
但是如果是直接命令行跑python脚本的话
先 pip install cloudscraper
然后把function_request.py里的from cfscrape import get_cookie_string 换成from cloudscraper import get_cookie_string 就行了

**Comment by gudejbvsoyczqu** [comment]
pip install cloudscraper
然后更新最新版1.09就可以了
