### ISSUE TITLE
Javlibrary通过五秒验证失败

### ISSUE THREAD

**Issue by Favorskii** [junerain123/javsdt#73]
Node.js本身可以使用且更新到最新版本，但是运行javlibrary.exe仍然有ERROR：Could not collect tokens，更换防屏蔽地址也没有用，请教一下如何解决。
PS：我在不挂梯子的情况下无法访问所有javlibrary网址，出现的问题和这个有关吗

**Comment by junerain123** [comment]
局部代理是无法通过javlibrary上的cloudflare检测，我不知道是cfscrape的缺陷，还是我的代码哪一步有问题。
全局是可以。
如果你访问javlibrary需要梯子，那么必须全局。

**Comment by Favorskii** [comment]
如您所说，更改VPN为全局后成功通过了检测，万分感谢
