### ISSUE TITLE
main_1.9.8文件在Mac系统下第613行 无法获取当前文件夹的上级目录

### ISSUE THREAD

**Issue by lqxx2005** [junerain123/javsdt#9]
![image](https://user-images.githubusercontent.com/15192261/70899757-3fdb1f00-2032-11ea-966b-d9ac4d19b54a.png)
![image](https://user-images.githubusercontent.com/15192261/70899774-4c5f7780-2032-11ea-923d-3292ac027b2e.png)

请问应该如何修改 才能获取上级目录

**Comment by junerain123** [comment]
`newroot_list = root.split('/')      # 视频文件当前所处的路径“root”，”以“/”切片成list
del newroot_list[-1]                   # 删除最后一项，就是删除视频文件当前的文件夹名称
upper2_root = '/'.join(newroot_list)  # 剩下来的再用“/”串起来，就是当前文件夹的上级文件夹路径
new_root = upper2_root + '/' + new_folder  # 上级文件夹路径+视频的新文件夹名称=视频的新文件夹路径`

**Comment by junerain123** [comment]
![44](https://user-images.githubusercontent.com/44168897/70901733-55eade80-2036-11ea-9347-f741d7b25a7a.PNG)

**Comment by junerain123** [comment]
还有一件事，别用1.9.8了，我发布了新的，变成了V1.0.0的新版本。

**Comment by lqxx2005** [comment]
感谢你的帮助 我已经用你的脚本替换我原来的。
